name: E2E Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  e2e:
    runs-on: ubuntu-latest

    services:
      web:
        image: automaticbytes/demo-app:latest
        ports:
          - 3100:3100

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          npm install
          npx playwright install --with-deps

      - name: Wait for demo-app to be available
        run: |
          echo "⏳ Waiting for http://localhost:3100/login ..."
          for i in $(seq 1 30); do
            if curl --silent --fail http://localhost:3100/login; then
              echo "✅ demo-app is up!"
              break
            fi
            echo "…still waiting ($i/30)"
            sleep 2
          done

      - name: Run Playwright tests
        env:
          BASE_URL: 'http://localhost:3100'
        run: npx playwright test

