name: E2E Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  e2e:
    runs-on: ubuntu-latest

    services:
      web:
        image: automaticbytes/demo-app:latest
        ports:
          - 3100:3100
        # simple healthcheck so tests wait until the app is ready
        options: >-
          --health-cmd="curl --silent --fail http://localhost:3100/health || exit 1"
          --health-interval=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          npm ci
          npx playwright install --with-deps

      - name: Run Playwright tests
        env:
          # point Playwright at the 'web' service via localhost:3100
          BASE_URL: 'http://localhost:3100'
        run: npx playwright test
