name: E2E Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  e2e:
    runs-on: ubuntu-latest
    services:
      web:
        image: automaticbytes/demo-app
        ports:
          - 3100:3100
        options: >-
          --health-cmd="curl --fail http://localhost:3100/ || exit 1"
          --health-interval=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          npm ci
          npx playwright install --with-deps

      - name: Wait for web app to be healthy
        run: |
          # waits until the healthcheck passes
          docker inspect --format='{{.State.Health.Status}}' $(docker ps -qf ancestor=automaticbytes/demo-app) \
            | grep healthy

      - name: Run Playwright tests
        run: npx playwright test

      - uses: actions/upload-artifact@master
        with:
          name: report-artifacts
          path: |
            playwright-report
          retention-days: 30

