name: E2E Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  e2e:
    runs-on: ubuntu-latest

    services:
      web:
        image: automaticbytes/demo-app:latest
        ports:
          - 3100:3100

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies & Playwright browsers
        run: |
          npm install
          npx playwright install --with-deps

      - name: Wait for demo-app
        run: |
          npm install -g wait-on
          echo "⏳ Waiting for http://localhost:3100/login to respond..."
          wait-on http://localhost:3100/login

      - name: Run Playwright tests
        env:
          BASE_URL: 'http://localhost:3100'
        run: npx playwright test

