name: E2E Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  e2e:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Pull and start demo-app
        run: |
          docker pull automaticbytes/demo-app:latest
          docker run -d --name demo-app -p 3100:3100 automaticbytes/demo-app

      - name: Wait for demo-app to be ready
        run: |
          echo "⏳ Waiting for http://localhost:3100 to respond..."
          for i in {1..30}; do
            if curl --silent --fail http://localhost:3100; then
              echo "✅ demo-app is up!"
              break
            fi
            echo "…still waiting ($i/30)"
            sleep 2
          done

      - name: Setup Node.js & install tests
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: |
          npm install
          npx playwright install --with-deps

      - name: Run Playwright tests
        env:
          BASE_URL: 'http://localhost:3100'
        run: npx playwright test

      - name: Tear down demo-app
        if: always()
        run: |
          docker stop demo-app
          docker rm demo-app

